Hw 5
polisgo2020/search-senyast4745 pull request #5
Opened 2020-04-06 19:49 UTC by senyast4745

hw 5 done

2020-04-08 12:30 UTC, tariel-x requested changes
Что-то я не вижу 
```
Необходимо разработать веб-интерфейс с 2-мя страницами: страница с полем ввода запроса и страница с результатами выдачи. Страница с результатами выдачи также должна содержать поле ввода.
```

2020-04-08 12:30 UTC, tariel-x commented on main.go
> +		logLvl = zerolog.InfoLevel
Не уверен, что это правильное поведение. Я бы лучше сделал выход из приложения в случае ошибки логов.

2020-04-08 12:30 UTC, tariel-x commented on main.go
> +func logMiddleware(next http.Handler) http.Handler {
Если есть пакет web, то, кажется, это в этом месте лишнее. И контроллер `r.Post("/` тоже.

2020-04-08 12:30 UTC, tariel-x commented on config/config.go
> +		instance = &Config{
Здорово было бы инициализировать структуру какими-нибудь значениями по-умолчанию, чтоб можно было сделать `go run main.go` и оно сразу заработало. Тогда и коде логгера и сервера не нужно было бы писать if-ы.

2020-04-08 12:31 UTC, tariel-x commented on config/config.go
> +		instance = &Config{
Это будет и просто удобнее для чтения кода другими людми: сразу понятно, какие значения по-умолчанию, как документацию почитать.

2020-04-08 12:39 UTC, senyast4745 commented
Это сделано не шаблонизатором просто. Это в nginx/static

2020-04-08 13:29 UTC, tariel-x commented
Статику можно раздавать и не через nginx, а тем же демоном. Это было бы намного проще для развёртывания, чем поднимать демон + nginx через docker-compose, который, к тому же, зависит от fluentd, который в другом docker-compose файле, который поднимается через COMPOSE_FILE. В котором лежит тяжёлый образ elastic.
Было бы здорово сделать `go run main.go` и что бы всё сразу работало.
Как минимум elastic в этой конструкции лишний, он относится не к этому проекту, а к инфраструктуре.

2020-04-08 13:36 UTC, tariel-x commented
Kibana, кстати, по-умолчанию не настроена и не позволяет сразу смотреть логи. Логи через `docker logs` не посмотреть, потому что драйвер другой, а контейнер с nginx почему-то не поднялся.

2020-04-08 16:14 UTC, senyast4745 commented
Хорошо) 
Хотел как лучше, получилось как всегда). 
Просто тогда вынуть всё из докера и логи просто в консоль?

2020-04-08 16:15 UTC, senyast4745 commented
Или настроить инфраструктуру?

2020-04-08 16:18 UTC, senyast4745 commented
Просто nginx я изначально решил как обратный прокси использовать для защиты backend. И nginx быстрее статику отдаёт, к тому же при смене порта на котором поднимается backend нужно просто немного изменить конфиги nginx, а не лезть в js

2020-04-08 16:23 UTC, senyast4745 commented
Или настроить fluentd

2020-04-08 20:43 UTC, senyast4745 commented
По поводу nginx. Я сторонник того чтобы фронтенд занимался фронтендом а бэкенд бэкендом. Поэтому я статику не раздаю демоном

2020-04-08 20:43 UTC, senyast4745 commented on main.go
> +func logMiddleware(next http.Handler) http.Handler {
Done

2020-04-08 20:43 UTC, senyast4745 commented on main.go
> +		logLvl = zerolog.InfoLevel
Done

2020-04-08 20:44 UTC, senyast4745 commented on config/config.go
> +		instance = &Config{
Done

2020-04-08 20:55 UTC, senyast4745 commented
Я попробовал на 3 компьютерах и везде работает)

2020-04-08 21:28 UTC, senyast4745 commented
Убрал Elastic steck теперь логи можно смотреть через docker logs

2020-04-09 21:41 UTC, tariel-x commented
> Хорошо)
> Хотел как лучше, получилось как всегда).
> Просто тогда вынуть всё из докера и логи просто в консоль или перенастроить flluentd?

Я бы вообще не засовывал сюда какую-либо инфраструктуру. Потому что это дело девопсов, как эксплуатировать демон. У них и репозитории могут быть свои собственные для конфигов и докер-композ им может быть лишним.

2020-04-09 21:45 UTC, senyast4745 commented
Тогда что лучше убрать/доделать/переделать?

И как там nginx? Завёлся?

2020-04-09 21:45 UTC, tariel-x commented
> По поводу nginx. Я сторонник того чтобы фронтенд занимался фронтендом а бэкенд бэкендом. Поэтому я статику не раздаю демоном

Ну в таком случае я бы всё равно не вставлял сюда nginx. Можно было бы оставить фронтэнд + написать доку/makefile/taskfile с каким-нибудь лёгким dev-сервером, чтоб чисто поднять фронтэнд. Или можно сделать в поисковом демоне что-то типа -devhttp флага, чтоб поднять фронт без лишних проблем.

Просто проблема в том, что то, как это будет эксплуатироваться - вообще не известно. Я, например, понятия не имею, где и как запускается код, который я пишу, кроме знания, что там kubernetes.

2020-04-09 21:52 UTC, tariel-x commented
Ну или, наверное, можно оставить docker-compose как сейчас, где будет только nginx и демон.  Просто очень странно смотрелся тот факт, что чтоб поднять маленький демонт + фронт у меня начались скачиваться тяжеленные образы es, хотя я лично не собирался ими пользовался и хотел бы читать логи через `docker logs`.

Кстати:
1. класть kibana, es в gitignore не лушая затея, потому что это только Ваше рабочее окружение. Лучше записать в .git/info/exclude
2. лишние docker-compose файлы всё ещё в индексе, несмотря на gitignore

2020-04-09 22:23 UTC, senyast4745 commented
Согласен. Решу утром

2020-04-09 22:31 UTC, senyast4745 commented
Последний вопрос. Лучше nginx или не nginx?

2020-04-10 19:14 UTC, tariel-x commented
> Последний вопрос. Лучше nginx или не nginx?

Не знаю. Главное, чтоб легко и быстро запускалось с минимумом телодвижений.

2020-04-10 19:34 UTC, senyast4745 commented
Хорошо, уберу nginx тогда наверное

2020-04-11 18:11 UTC, tariel-x commented
Можно попробовать написать похожий docker-compose:
```yaml
version: '3.3'

services:
  frontend:
    image: caddy/caddy
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes: 
      - ./static/:/usr/share/caddy/

  backend:
    build: .
    environment:
      - LOG_LEVEL=debug
      - IND_FILE=final.csv
      - LISTEN=0.0.0.0:80
    ports:
      - 8081:80
    volumes:
      - ./output:/output
```

2020-04-11 22:23 UTC, senyast4745 commented
А чем caddy лучше nginx? Весит меньше или быстрее?

2020-04-13 10:12 UTC, tariel-x commented
> А чем caddy лучше nginx? Быстрее?
> Образ caddy просто в два раза тяжелее

caddy не быстрее, но, как видно из примера, настраивается много проще. И 52мб против 21 не так критично:
```
$ docker images | grep "nginx\|caddy"
caddy/caddy                                            latest              427f08d77d16        21 hours ago        52.3MB
nginx                                                  latest              ed21b7a8aee9        13 days ago         127MB
nginx                                                  stable-alpine       5fad07aba15a        2 months ago        21.8MB

```

2020-04-13 18:05 UTC, senyast4745 commented
Могу тогда я закрыт пр? Не захотел переезжать на caddy. Не очень понравилось)

2020-04-14 18:40 UTC, tariel-x commented
> Могу тогда я закрыт пр? Не захотел переезжать на caddy. Не очень понравилось)

Закрыть или вмержить? Тут осталось много на мой взгляд лишних вещей, типа docker-compose-logs.yml.

2020-04-14 18:49 UTC, senyast4745 commented
Логи уберу. Что ещё осталось?

2020-04-15 18:28 UTC, tariel-x approved these changes

2020-04-16 11:57 UTC, merged